server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://${STATS_DB_HOST}:${STATS_DB_PORT}/${STATS_DB_NAME}
    username: ${STATS_DB_USERNAME}
    password: ${STATS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:stats-schema.sql
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            INFO
        transaction:
          INFO
---
#TEST CONFIG
spring:
  config:
    activate:
      on-profile: ci,test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:explore
    username: test
    password: test