server:
  port:8080
stats.server.url: ${EWM_STATS_SERVICE_URL}
spring:
  datasource:
    url: jdbc:postgresql://${EWM_DB_HOST}:${EWM_DB_PORT}/${EWM_DB_NAME}
    username: ${EWM_DB_USERNAME}
    password: ${EWM_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:main-service-schema.sql
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            INFO
        transaction:
          INFO
---
#TEST CONFIG
spring:
  config:
    activate:
      on-profile: ci,test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:explore
    username: test
    password: test