version: '3.8'

services:
  stats-server:
    build:
      context: ./stats-service/stats-server
    container_name: jewm_stats_service_container
    ports:
      - "9090:9090"
    environment:
      - STATS_DB_HOST=stats-db
      - STATS_DB_NAME=stats
      - STATS_DB_PORT=5432
      - STATS_DB_USERNAME=dbuser
      - STATS_DB_PASSWORD=12345
    depends_on:
      stats-db:
        condition: service_healthy

  stats-db:
    image: postgres:16.1
    container_name: jewm_stats_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build:
      context: ./main-service
    container_name: jewm_service_container
    ports:
      - "8080:8080"
    environment:
      - EWM_DB_HOST=ewm-db
      - EWM_DB_NAME=main
      - EWM_DB_PORT=5432
      - EWM_DB_USERNAME=dbuser
      - EWM_DB_PASSWORD=12345
      - EWM_STATS_SERVICE_URL=http://stats-server:9090
    depends_on:
      stats-db:
        condition: service_healthy
      ewm-db:
        condition: service_healthy

  ewm-db:
    image: postgres:16.1
    container_name: jewm_db
    ports:
      - "6544:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=main
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
